### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by emulienfou** [moay/symfony-flex-server#18] opened 2018-10-06 18:52 UTC
In the next line of code, sometimes the `json_encode()` function return false due to a malformed UTF8 encoding.
https://github.com/moay/symfony-flex-server/blob/e3de35315172942651164c8a405e37649167a4f6/src/Traits/ProvidesUnescapedJsonResponsesTrait.php#L32

In my case, my recipe contain a `favicon.ico` file who need to be encoded in UTF8 to avoid this kind of unwanted result.

To fix this problem, I had to convert latin to UTF8 content like:
```php
trait ProvidesUnescapedJsonResponsesTrait
{
    /**
     * @param $data
     * @param int $status
     * @param array $headers
     * @param array $context
     * @return static
     */
    protected function json($data, int $status = 200, array $headers = array(), array $context = array()): JsonResponse
    {
        $json = json_encode($data, JSON_UNESCAPED_SLASHES);
        if (false === $json){
            $data = self::convertFromLatin1ToUtf8Recursively($data);
            $json = json_encode($data, JSON_UNESCAPED_SLASHES);
        }
        return JsonResponse::fromJsonString($json, $status, $headers);
    }

    /**
     * Encode array from latin1 to utf8 recursively
     * @param $dat
     * @see https://stackoverflow.com/a/38398648
     * @return array|bool|string
     */
    public static function convertFromLatin1ToUtf8Recursively($dat)
    {
        if (is_string($dat)) {
            return utf8_encode($dat);
        } elseif (is_array($dat)) {
            $ret = [];
            foreach ($dat as $i => $d) {
                $ret[$i] = self::convertFromLatin1ToUtf8Recursively($d);
            }

            return $ret;
        } elseif (is_object($dat)) {
            foreach ($dat as $i => $d) {
                $dat->$i = self::convertFromLatin1ToUtf8Recursively($d);
            }

            return $dat;
        }

        return $dat;
    }
}
```

Hope this will help anyone who has the same issue.

**Comment by moay** [comment] 2019-04-18 12:42
Couldn't reproduce, closing for now. Feel free to reopen this it you feel that this is an issue for many people and needs to be addressed.

**Closed by moay** 2019-04-18 12:42 UTC
